version: "3.9"
services:
  ubvnc-odyssey-x86j4125-code:
    build: 
      context: ../
      dockerfile: ./common/code/Dockerfile
      args:
        - OPENWRT_VERSION=22.03.2
        # check https://openwrt.org/docs/guide-developer/toolchain/install-buildsystem#debianubuntu for dependencies
        - >-
             PACKAGES_INSTALL=
             build-essential ccache ecj fastjar file g++ gawk
             gettext git java-propose-classpath libelf-dev libncurses5-dev
             libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget
             python3-distutils python3-setuptools python3-dev rsync subversion
             swig time xsltproc zlib1g-dev ssh protobuf-c-compiler
    ports:
      - "6080:80"
      - "5900:5900"
    volumes:
      - ./config:/root/openwrt_config
      - ./files:/root/openwrt_files
      - ./binaries/code:/root/Desktop/openwrt/bin/targets/x86
      - ./binaries/imagebuilder:/root/Desktop/openwrt-imagebuilder/bin/targets/x86
    entrypoint:
      - /bin/sh
      - -c
      - |
          # Convert /r/n (Windows) into /n (Unix)
          sed -i 's/\r//g' /root/openwrt_files/etc/uci-defaults/99-increase-disk-size
          sed -i 's/\r//g' /root/openwrt_files/etc/uci-defaults/99-uci-config
          sed -i 's/\r//g' /root/openwrt_files/etc/sysctl.d/99-nlbwmon_fix.conf
          # Remove files so we can link them to the outside
          rm /root/Desktop/openwrt/.config
          rm /root/Desktop/openwrt/target/linux/x86/config-5.10
          rm -r /root/Desktop/openwrt/files 
          # Create links so files are updated with outside content
          ln -s /root/openwrt_config/config /root/Desktop/openwrt/.config
          ln -s /root/openwrt_config/kconfig /root/Desktop/openwrt/target/linux/x86/config-5.10
          ln -s -T /root/openwrt_files /root/Desktop/openwrt/files
          ln -s -T /root/openwrt_files /root/Desktop/openwrt-imagebuilder/files
          #cp -ru /root/Desktop/openwrt/.bin/targets/x86/64 /root/Desktop/openwrt/bin/targets/x86
          /startup.sh
    environment:
      # To use with the compiled image builder, can't use the one on openwrt binary repo since it contains a kernel that will not work
      # Check more info https://openwrt.org/docs/guide-user/additional-software/imagebuilder
      - >-
        PACKAGES=
        -libustream-wolfssl
        acl
        amd64-microcode
        amdgpu-firmware
        attr
        base-files
        bash
        block-mount
        blockd
        bsdtar
        busybox
        bzip2
        ca-bundle
        ca-certificates
        cgi-io
        dmidecode
        dnslookup
        dropbear
        e2fsprogs
        ethtool-full
        fdisk
        firewall4
        fstools
        fwtool
        getrandom
        grub2
        grub2-bios-setup
        grub2-efi
        gzip
        hostapd-common
        hwinfo
        ibt-firmware
        intel-microcode
        ip6tables-nft
        iptables-mod-ipopt
        iptables-nft
        iucode-tool
        iw
        iwinfo
        iwlwifi-firmware-iwl9000
        jansson4
        jshn
        jsonfilter
        kernel
        kmod-6lowpan
        kmod-9pnet
        kmod-aoe
        kmod-asn1-decoder
        kmod-ata-ahci
        kmod-ata-core
        kmod-ata-marvell-sata
        kmod-ata-nvidia-sata
        kmod-ata-piix
        kmod-ata-sil
        kmod-ata-sil24
        kmod-ata-via-sata
        kmod-backlight
        kmod-backlight-pwm
        kmod-block2mtd
        kmod-bluetooth
        kmod-bluetooth-6lowpan
        kmod-cdrom
        kmod-cfg80211
        kmod-chaoskey
        kmod-crypto-acompress
        kmod-crypto-aead
        kmod-crypto-arc4
        kmod-crypto-authenc
        kmod-crypto-cbc
        kmod-crypto-ccm
        kmod-crypto-cmac
        kmod-crypto-crc32
        kmod-crypto-crc32c
        kmod-crypto-ctr
        kmod-crypto-cts
        kmod-crypto-deflate
        kmod-crypto-des
        kmod-crypto-ecb
        kmod-crypto-ecdh
        kmod-crypto-echainiv
        kmod-crypto-fcrypt
        kmod-crypto-gcm
        kmod-crypto-gf128
        kmod-crypto-ghash
        kmod-crypto-hash
        kmod-crypto-hmac
        kmod-crypto-kpp
        kmod-crypto-manager
        kmod-crypto-md4
        kmod-crypto-md5
        kmod-crypto-michael-mic
        kmod-crypto-null
        kmod-crypto-pcbc
        kmod-crypto-rng
        kmod-crypto-seqiv
        kmod-crypto-sha1
        kmod-crypto-sha256
        kmod-crypto-sha512
        kmod-dax
        kmod-dm
        kmod-dma-buf
        kmod-dnsresolver
        kmod-drm
        kmod-drm-amdgpu
        kmod-drm-kms-helper
        kmod-drm-radeon
        kmod-drm-ttm
        kmod-fb
        kmod-fb-cfb-copyarea
        kmod-fb-cfb-fillrect
        kmod-fb-cfb-imgblt
        kmod-fb-sys-fops
        kmod-fb-sys-ram
        kmod-fb-tft
        kmod-fb-tft-ili9486
        kmod-fixed-phy
        kmod-fs-9p
        kmod-fs-antfs
        kmod-fs-autofs4
        kmod-fs-btrfs
        kmod-fs-cifs
        kmod-fs-configfs
        kmod-fs-cramfs
        kmod-fs-efivarfs
        kmod-fs-exfat
        kmod-fs-exportfs
        kmod-fs-ext4
        kmod-fs-f2fs
        kmod-fs-fscache
        kmod-fs-hfs
        kmod-fs-hfsplus
        kmod-fs-isofs
        kmod-fs-jfs
        kmod-fs-ksmbd
        kmod-fs-minix
        kmod-fs-msdos
        kmod-fs-nfs
        kmod-fs-nfs-common
        kmod-fs-nfs-common-rpcsec
        kmod-fs-nfs-v3
        kmod-fs-nfs-v4
        kmod-fs-nfsd
        kmod-fs-ntfs
        kmod-fs-reiserfs
        kmod-fs-squashfs
        kmod-fs-udf
        kmod-fs-vfat
        kmod-fs-xfs
        kmod-fuse
        kmod-gre
        kmod-gre6
        kmod-hid
        kmod-hid-generic
        kmod-hwmon-core
        kmod-i2c-algo-bit
        kmod-i2c-core
        kmod-ifb
        kmod-igb
        kmod-ikconfig
        kmod-input-core
        kmod-input-evdev
        kmod-iosched-bfq
        kmod-ip6-tunnel
        kmod-ip6tables
        kmod-ipt-core
        kmod-ipt-ipopt
        kmod-iptunnel
        kmod-iptunnel6
        kmod-irqbypass
        kmod-iwlwifi
        kmod-keys-encrypted
        kmod-keys-trusted
        kmod-kvm-intel
        kmod-kvm-x86
        kmod-lib-cordic
        kmod-lib-crc-ccitt
        kmod-lib-crc-itu-t
        kmod-lib-crc16
        kmod-lib-crc32c
        kmod-lib-crc8
        kmod-lib-lzo
        kmod-lib-raid6
        kmod-lib-textsearch
        kmod-lib-xor
        kmod-lib-zlib-deflate
        kmod-lib-zlib-inflate
        kmod-lib-zstd
        kmod-libphy
        kmod-libsas
        kmod-loop
        kmod-mac80211
        kmod-mii
        kmod-mmc
        kmod-mvsas
        kmod-nbd
        kmod-nf-conntrack
        kmod-nf-conntrack6
        kmod-nf-flow
        kmod-nf-ipt
        kmod-nf-ipt6
        kmod-nf-log
        kmod-nf-log6
        kmod-nf-nat
        kmod-nf-reject
        kmod-nf-reject6
        kmod-nfnetlink
        kmod-nft-compat
        kmod-nft-core
        kmod-nft-fib
        kmod-nft-nat
        kmod-nft-offload
        kmod-nls-base
        kmod-nls-cp437
        kmod-nls-iso8859-1
        kmod-nls-utf8
        kmod-oid-registry
        kmod-phy-ax88796b
        kmod-phy-microchip
        kmod-phy-smsc
        kmod-pps
        kmod-pstore
        kmod-ptp
        kmod-random-core
        kmod-regmap-core
        kmod-sched-cake
        kmod-sched-core
        kmod-scsi-cdrom
        kmod-scsi-core
        kmod-scsi-generic
        kmod-sdhci
        kmod-spi-bitbang
        kmod-ssb
        kmod-tpm
        kmod-usb-cm109
        kmod-usb-core
        kmod-usb-dwc2
        kmod-usb-dwc3
        kmod-usb-ehci
        kmod-usb-hid
        kmod-usb-hid-cp2112
        kmod-usb-ledtrig-usbport
        kmod-usb-ohci
        kmod-usb-ohci-pci
        kmod-usb-roles
        kmod-usb-serial
        kmod-usb-serial-ark3116
        kmod-usb-serial-belkin
        kmod-usb-serial-ch341
        kmod-usb-serial-cp210x
        kmod-usb-serial-cypress-m8
        kmod-usb-serial-dmx_usb_module
        kmod-usb-serial-ftdi
        kmod-usb-serial-garmin
        kmod-usb-serial-keyspan
        kmod-usb-serial-mct
        kmod-usb-serial-mos7720
        kmod-usb-serial-mos7840
        kmod-usb-serial-option
        kmod-usb-serial-oti6858
        kmod-usb-serial-pl2303
        kmod-usb-serial-qualcomm
        kmod-usb-serial-sierrawireless
        kmod-usb-serial-simple
        kmod-usb-serial-ti-usb
        kmod-usb-serial-visor
        kmod-usb-serial-wwan
        kmod-usb-serial-xr_usb_serial_common
        kmod-usb-storage
        kmod-usb-storage-extras
        kmod-usb-storage-uas
        kmod-usb-uhci
        kmod-usb-wdm
        kmod-usb-xhci-hcd
        kmod-usb-yealink
        kmod-usb2
        kmod-usb2-pci
        kmod-usb3
        kmod-usbip
        kmod-usbip-client
        kmod-usbip-server
        kmod-usbmon
        kmod-v4l2loopback
        kmod-video-core
        kmod-video-cpia2
        kmod-video-gspca-conex
        kmod-video-gspca-core
        kmod-video-gspca-etoms
        kmod-video-gspca-finepix
        kmod-video-gspca-gl860
        kmod-video-gspca-jeilinj
        kmod-video-gspca-konica
        kmod-video-gspca-m5602
        kmod-video-gspca-mars
        kmod-video-gspca-mr97310a
        kmod-video-gspca-ov519
        kmod-video-gspca-ov534
        kmod-video-gspca-ov534-9
        kmod-video-gspca-pac207
        kmod-video-gspca-pac7311
        kmod-video-gspca-se401
        kmod-video-gspca-sn9c20x
        kmod-video-gspca-sonixb
        kmod-video-gspca-sonixj
        kmod-video-gspca-spca500
        kmod-video-gspca-spca501
        kmod-video-gspca-spca505
        kmod-video-gspca-spca506
        kmod-video-gspca-spca508
        kmod-video-gspca-spca561
        kmod-video-gspca-sq905
        kmod-video-gspca-sq905c
        kmod-video-gspca-sq930x
        kmod-video-gspca-stk014
        kmod-video-gspca-stv06xx
        kmod-video-gspca-sunplus
        kmod-video-gspca-t613
        kmod-video-gspca-tv8532
        kmod-video-gspca-vc032x
        kmod-video-gspca-zc3xx
        kmod-video-pwc
        kmod-video-uvc
        kmod-video-videobuf2
        libacl
        libarchive
        libatomic1
        libattr
        libblkid1
        libblobmsg-json20220515
        libbz2-1.0
        libc
        libcap
        libcomerr0
        libdbus
        libdevmapper
        libevent2-core7
        libexpat
        libext2fs2
        libfdisk1
        libgcc1
        libgmp10
        libgnutls
        libiconv-full2
        libiptext-nft0
        libiptext0
        libiptext6-0
        libiwinfo-data
        libiwinfo-lua
        libiwinfo20210430
        libjson-c5
        libjson-script20220515
        liblua5.1.5
        liblucihttp-lua
        liblucihttp0
        liblz4-1
        liblzma
        liblzo2
        libmnl0
        libmount1
        libncurses6
        libnettle8
        libnftnl11
        libnl-tiny1
        libopenssl-conf
        libopenssl1.1
        libparted
        libpthread
        libreadline8
        librt
        libsmartcols1
        libss2
        libstdcpp6
        libubox20220515
        libubus-lua
        libubus20220601
        libuci20130104
        libuclient20201210
        libucode20220812
        libuuid1
        libuv1
        libwebsockets-full
        libxtables12
        libzip-gnutls
        libzstd
        logd
        lsblk
        lua
        luci
        luci-app-firewall
        luci-app-opkg
        luci-app-ttyd
        luci-base
        luci-i18n-base-en
        luci-i18n-firewall-en
        luci-i18n-opkg-en
        luci-i18n-ttyd-en
        luci-lib-base
        luci-lib-ip
        luci-lib-jsonc
        luci-lib-nixio
        luci-mod-admin-full
        luci-mod-network
        luci-mod-status
        luci-mod-system
        luci-proto-ipv6
        luci-proto-ppp
        luci-theme-bootstrap
        luci-theme-material
        luci-theme-openwrt
        luci-theme-openwrt-2020
        lz4
        lzmadec
        lzmainfo
        mount-utils
        mtd
        musl-fts
        nano-full
        netifd
        nftables-json
        ntpclient
        openwrt-keyring
        opkg
        parted
        partx-utils
        pigz
        procd
        procd-seccomp
        procd-ujail
        radeon-firmware
        resolveip
        rpcd
        rpcd-mod-file
        rpcd-mod-iwinfo
        rpcd-mod-luci
        rpcd-mod-rpcsys
        rpcd-mod-rrdns
        rpcd-mod-ucode
        sqm-scripts
        tc-tiny
        terminfo
        ttyd
        ubox
        ubus
        ubusd
        uci
        uclient-fetch
        ucode
        ucode-mod-fs
        ucode-mod-ubus
        ucode-mod-uci
        uhttpd
        uhttpd-mod-ubus
        unrar
        unzip
        urandom-seed
        urngd
        usign
        wireless-regdb
        xtables-nft
        xz
        xz-utils
        xzdec
        xzdiff
        xzgrep
        xzless
        xzmore
        zipcmp
        zipmerge
        ziptool
        zlib
        zstd
